name: forensic
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animated_notch_bottom_bar: ^1.0.3
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  modern_textfield: ^0.0.6
  path: ^1.9.0
  googleapis_auth: ^1.6.0
  file_picker: ^9.0.0
  http: ^1.3.0
  googleapis: ^13.2.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  url_launcher: ^6.3.1
  pdf: ^3.11.3
  printing: ^5.14.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/user.json
    - assets/bg.jpg
    - assets/bger.png
    - assets/logo.png
    - assets/jawu.jpg
    - assets/jawl.jpg
    - assets/bg2.jpg
